runtime: python
env: flex
entrypoint: gunicorn -b :$PORT patient:app

runtime_config:
    python_version: 3

handlers:
- url: .*
  script: clerk.app

- url: /favicon\.ico
  static_files: static/MAPS_ICON.png
  upload: static/MAPS_ICON\.png

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10